INSERT INTO tb_pais (code,nome) VALUES
	 (1,'Brasil'),
	 (2,'Afeganistão'),
	 (3,'Albânia, Republica da'),
	 (4,'Argélia'),
	 (5,'Samoa Americana'),
	 (6,'Andorra'),
	 (7,'Angola'),
	 (8,'Anguilla'),
	 (9,'Antártida'),
	 (10,'Antigua e Barbuda');
INSERT INTO tb_pais (code,nome) VALUES
	 (11,'Argentina'),
	 (12,'Armênia, Republica da'),
	 (13,'Aruba'),
	 (14,'Austrália'),
	 (15,'Áustria'),
	 (16,'Azerbaijão, Republica do'),
	 (17,'Bahamas, Ilhas'),
	 (18,'Bahrein, Ilhas'),
	 (19,'Bangladesh'),
	 (20,'Barbados');
INSERT INTO tb_pais (code,nome) VALUES
	 (21,'Belarus, Republica da'),
	 (22,'Bélgica'),
	 (23,'Belize'),
	 (24,'Benin'),
	 (25,'Bermudas'),
	 (26,'Butão'),
	 (27,'Bolívia'),
	 (28,'Bósnia-herzegovina (Republica da)'),
	 (29,'Botsuana'),
	 (30,'Bouvet, Ilha');
INSERT INTO tb_pais (code,nome) VALUES
	 (31,'Território Britânico do Oceano Indico'),
	 (32,'Brunei'),
	 (33,'Bulgária, Republica da'),
	 (34,'Burkina Faso'),
	 (35,'Burundi'),
	 (36,'Camboja'),
	 (37,'Camarões'),
	 (38,'Canada'),
	 (39,'Cabo Verde, Republica de'),
	 (40,'Cayman, Ilhas');
INSERT INTO tb_pais (code,nome) VALUES
	 (41,'Republica Centro-Africana'),
	 (42,'Chade'),
	 (43,'Chile'),
	 (44,'China, Republica Popular'),
	 (45,'Christmas, Ilha (Navidad)'),
	 (46,'Cocos (Keeling), Ilhas'),
	 (47,'Colômbia'),
	 (48,'Comores, Ilhas'),
	 (49,'Congo'),
	 (50,'Congo, Republica Democrática do');
INSERT INTO tb_pais (code,nome) VALUES
	 (51,'Cook, Ilhas'),
	 (52,'Costa Rica'),
	 (53,'Costa do Marfim'),
	 (54,'Croácia (Republica da)'),
	 (55,'Cuba'),
	 (56,'Chipre'),
	 (57,'Tcheca, Republica'),
	 (58,'Dinamarca'),
	 (59,'Djibuti'),
	 (60,'Dominica, Ilha');
INSERT INTO tb_pais (code,nome) VALUES
	 (61,'Republica Dominicana'),
	 (62,'Timor Leste'),
	 (63,'Equador'),
	 (64,'Egito'),
	 (65,'El Salvador'),
	 (66,'Guine-Equatorial'),
	 (67,'Eritreia'),
	 (68,'Estônia, Republica da'),
	 (69,'Etiópia'),
	 (70,'Falkland (Ilhas Malvinas)');
INSERT INTO tb_pais (code,nome) VALUES
	 (71,'Feroe, Ilhas'),
	 (72,'Fiji'),
	 (73,'Finlândia'),
	 (74,'Franca'),
	 (76,'Guiana francesa'),
	 (77,'Polinésia Francesa'),
	 (78,'Terras Austrais e Antárticas Francesas'),
	 (79,'Gabão'),
	 (80,'Gambia'),
	 (81,'Georgia, Republica da');
INSERT INTO tb_pais (code,nome) VALUES
	 (82,'Alemanha'),
	 (83,'Gana'),
	 (84,'Gibraltar'),
	 (85,'Grécia'),
	 (86,'Groenlândia'),
	 (87,'Granada'),
	 (88,'Guadalupe'),
	 (89,'Guam'),
	 (90,'Guatemala'),
	 (91,'Guine');
INSERT INTO tb_pais (code,nome) VALUES
	 (92,'Guine-Bissau'),
	 (93,'Guiana'),
	 (94,'Haiti'),
	 (95,'Ilha Heard e Ilhas McDonald'),
	 (96,'Vaticano, Estado da Cidade do'),
	 (97,'Honduras'),
	 (98,'Hong Kong'),
	 (99,'Hungria, Republica da'),
	 (100,'Islândia'),
	 (101,'Índia');
INSERT INTO tb_pais (code,nome) VALUES
	 (102,'Indonésia'),
	 (103,'Ira, Republica Islâmica do'),
	 (104,'Iraque'),
	 (105,'Irlanda'),
	 (106,'Israel'),
	 (107,'Itália'),
	 (108,'Jamaica'),
	 (109,'Japão'),
	 (110,'Jordânia'),
	 (111,'Cazaquistão, Republica do');
INSERT INTO tb_pais (code,nome) VALUES
	 (112,'Quênia'),
	 (113,'Kiribati'),
	 (114,'Coreia, Republica Popular Democrática da'),
	 (115,'Coreia, Republica da'),
	 (116,'Kuwait'),
	 (117,'Quirguiz, Republica'),
	 (118,'Laos, Republica Popular Democrática do'),
	 (119,'Letônia, Republica da'),
	 (120,'Líbano'),
	 (121,'Lesoto');
INSERT INTO tb_pais (code,nome) VALUES
	 (122,'Libéria'),
	 (123,'Líbia'),
	 (124,'Liechtenstein'),
	 (125,'Lituânia, Republica da'),
	 (126,'Luxemburgo'),
	 (127,'Macau'),
	 (128,'Macedônia do Norte'),
	 (129,'Madagascar'),
	 (130,'Malavi'),
	 (131,'Malásia');
INSERT INTO tb_pais (code,nome) VALUES
	 (132,'Maldivas'),
	 (133,'Mali'),
	 (134,'Malta'),
	 (135,'Marshall, Ilhas'),
	 (136,'Martinica'),
	 (137,'Mauritânia'),
	 (138,'Mauricio'),
	 (139,'Mayotte (Ilhas Francesas)'),
	 (140,'México'),
	 (141,'Micronesia');
INSERT INTO tb_pais (code,nome) VALUES
	 (142,'Moldávia, Republica da'),
	 (143,'Mônaco'),
	 (144,'Mongólia'),
	 (145,'Montserrat, Ilhas'),
	 (146,'Marrocos'),
	 (147,'Moçambique'),
	 (148,'Mianmar (Birmânia)'),
	 (149,'Namíbia'),
	 (150,'Nauru'),
	 (151,'Nepal');
INSERT INTO tb_pais (code,nome) VALUES
	 (152,'Países Baixos (Holanda)'),
	 (154,'Nova Caledonia'),
	 (155,'Nova Zelândia'),
	 (156,'Nicarágua'),
	 (157,'Níger'),
	 (158,'Nigéria'),
	 (159,'Niue, Ilha'),
	 (160,'Norfolk, Ilha'),
	 (161,'Marianas do Norte'),
	 (162,'Noruega');
INSERT INTO tb_pais (code,nome) VALUES
	 (163,'Oma'),
	 (164,'Paquistão'),
	 (165,'Palau'),
	 (166,'Panamá'),
	 (167,'Papua Nova Guine'),
	 (168,'Paraguai'),
	 (169,'Peru'),
	 (170,'Filipinas'),
	 (171,'Pitcairn, Ilha'),
	 (172,'Polônia, Republica da');
INSERT INTO tb_pais (code,nome) VALUES
	 (173,'Portugal'),
	 (174,'Porto Rico'),
	 (175,'Catar'),
	 (176,'Reunião, Ilha'),
	 (177,'Romênia'),
	 (178,'Rússia, Federação da'),
	 (179,'Ruanda'),
	 (180,'São Cristovão e Neves, Ilhas'),
	 (181,'Santa Lucia'),
	 (182,'São Vicente e Granadinas');
INSERT INTO tb_pais (code,nome) VALUES
	 (183,'Samoa'),
	 (184,'San Marino'),
	 (185,'São Tome e Príncipe, Ilhas'),
	 (186,'Arábia Saudita'),
	 (187,'Senegal'),
	 (188,'Seychelles'),
	 (189,'Serra Leoa'),
	 (190,'Cingapura'),
	 (191,'Eslovaca, Republica'),
	 (192,'Eslovênia, Republica da');
INSERT INTO tb_pais (code,nome) VALUES
	 (193,'Salomão, Ilhas'),
	 (194,'Somalia'),
	 (195,'África do Sul'),
	 (196,'Ilhas Geórgia do Sul e Sandwich do Sul'),
	 (197,'Espanha'),
	 (198,'Sri Lanka'),
	 (199,'Santa Helena'),
	 (200,'São Pedro e Miquelon'),
	 (201,'Sudão'),
	 (202,'Suriname');
INSERT INTO tb_pais (code,nome) VALUES
	 (203,'Svalbard e Jan Mayen'),
	 (204,'Eswatini'),
	 (205,'Suécia'),
	 (206,'Suíça'),
	 (207,'Síria, Republica Árabe da'),
	 (208,'Formosa (Taiwan)'),
	 (209,'Tadjiquistao, Republica do'),
	 (210,'Tanzânia, Republica Unida da'),
	 (211,'Tailândia'),
	 (212,'Togo');
INSERT INTO tb_pais (code,nome) VALUES
	 (213,'Toquelau, Ilhas'),
	 (214,'Tonga'),
	 (215,'Trinidad e Tobago'),
	 (216,'Tunísia'),
	 (217,'Turquia'),
	 (218,'Turcomenistão, Republica do'),
	 (219,'Turcas e Caicos, Ilhas'),
	 (220,'Tuvalu'),
	 (221,'Uganda'),
	 (222,'Ucrânia');
INSERT INTO tb_pais (code,nome) VALUES
	 (223,'Emirados Árabes Unidos'),
	 (224,'Reino Unido'),
	 (225,'Estados Unidos'),
	 (226,'Ilhas Menores Distantes dos Estados Unidos'),
	 (227,'Uruguai'),
	 (228,'Uzbequistão, Republica do'),
	 (229,'Vanuatu'),
	 (230,'Venezuela'),
	 (231,'Vietnã'),
	 (232,'Virgens, Ilhas (Britânicas)');
INSERT INTO tb_pais (code,nome) VALUES
	 (233,'Virgens, Ilhas (E.U.A.)'),
	 (234,'Wallis e Futuna, Ilhas'),
	 (235,'Saara Ocidental'),
	 (236,'Iémen'),
	 (237,'Iugoslávia, República Fed. da'),
	 (238,'Zâmbia'),
	 (239,'Zimbabue'),
	 (240,'Guernsey, Ilha do Canal (Inclui Alderney e Sark)'),
	 (241,'Jersey, Ilha do Canal'),
	 (243,'Man, Ilha de');
INSERT INTO tb_pais (code,nome) VALUES
	 (246,'Montenegro'),
	 (247,'Republika Srbija'),
	 (248,'Sudao do Sul'),
	 (249,'Zona do Canal do Panamá'),
	 (252,'Palestina'),
	 (253,'Aland, Ilhas'),
	 (255,'Curaçao'),
	 (256,'São Martinho, Ilha de (Parte Holandesa)'),
	 (258,'Bonaire'),
	 (259,'Antartica');
INSERT INTO tb_pais (code,nome) VALUES
	 (260,'Ilha Herad e Ilhas Macdonald'),
	 (261,'São Bartolomeu'),
	 (262,'São Martinho, Ilha de (Parte Francesa)'),
	 (263,'Terras Austrais e Antárcticas Francesas');